export const nationalityFlags: { [key: string]: string } = {
  // Nationalities and Countries (as stored in players.nationality)
  "Albanian": "🇦🇱",
  "Albania": "🇦🇱",
  "Algerian": "🇩🇿",
  "Algeria": "🇩🇿",
  "American": "🇺🇸",
  "USA": "🇺🇸",
  "United States": "🇺🇸",
  "United States of America": "🇺🇸",
  "United States of America A": "🇺🇸",
  "United States of America B": "🇺🇸",
  "Andorran": "🇦🇩",
  "Andorra": "🇦🇩",
  "Angolan": "🇦🇴",
  "Angola": "🇦🇴",
  "Argentinian": "🇦🇷",
  "Argentina": "🇦🇷",
  "Armenian": "🇦🇲",
  "Armenia": "🇦🇲",
  "Australian": "🇦🇺",
  "Australia": "🇦🇺",
  "Austrian": "🇦🇹",
  "Austria": "🇦🇹",
  "Azerbaijani": "🇦🇿",
  "Azerbaijan": "🇦🇿",
  "Bahraini": "🇧🇭",
  "Bahrain": "🇧🇭",
  "Bangladeshi": "🇧🇩",
  "Bangladesh": "🇧🇩",
  "Belarusian": "🇧🇾",
  "Belarus": "🇧🇾",
  "Belgian": "🇧🇪",
  "Belgium": "🇧🇪",
  "Beninese": "🇧🇯",
  "Benin": "🇧🇯",
  "Bolivian": "🇧🇴",
  "Bolivia": "🇧🇴",
  "Bosnian": "🇧🇦",
  "Bosnia-Herzegovina": "🇧🇦",
  "Brazilian": "🇧🇷",
  "Brazil": "🇧🇷",
  "Bulgarian": "🇧🇬",
  "Bulgaria": "🇧🇬",
  "Burkinabe": "🇧🇫",
  "Burundi": "🇧🇮",
  "Cambodian": "🇰🇭",
  "Cambodia": "🇰🇭",
  "Cameroonian": "🇨🇲",
  "Cameroon": "🇨🇲",
  "Canadian": "🇨🇦",
  "Canada": "🇨🇦",
  "Cape Verdean": "🇨🇻",
  "Chilean": "🇨🇱",
  "Chile": "🇨🇱",
  "Chinese": "🇨🇳",
  "China": "🇨🇳",
  "Colombian": "🇨🇴",
  "Colombia": "🇨🇴",
  "Costa Rican": "🇨🇷",
  "Costa Rica": "🇨🇷",
  "Croatian": "🇭🇷",
  "Croatia": "🇭🇷",
  "Cypriot": "🇨🇾",
  "Cyprus": "🇨🇾",
  "Czech": "🇨🇿",
  "Czech Republic": "🇨🇿",
  "Danish": "🇩🇰",
  "Denmark": "🇩🇰",
  "Dutch": "🇳🇱",
  "Netherlands": "🇳🇱",
  "Ecuadorian": "🇪🇨",
  "Ecuador": "🇪🇨",
  "Egyptian": "🇪🇬",
  "Egypt": "🇪🇬",
  "Emirati": "🇦🇪",
  "United Arab Emirates": "🇦🇪",
  "English": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "England 4th": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "England 5th": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "Estonian": "🇪🇪",
  "Estonia": "🇪🇪",
  "Faroese": "🇫🇴",
  "Faroe Islands": "🇫🇴",
  "Fijian": "🇫🇯",
  "Fiji": "🇫🇯",
  "Finnish": "🇫🇮",
  "Finland": "🇫🇮",
  "French": "🇫🇷",
  "France": "🇫🇷",
  "Georgian": "🇬🇪",
  "Georgia": "🇬🇪",
  "German": "🇩🇪",
  "Germany": "🇩🇪",
  "Ghanaian": "🇬🇭",
  "Ghana": "🇬🇭",
  "Greek": "🇬🇷",
  "Greece": "🇬🇷",
  "Guatemalan": "🇬🇹",
  "Guatemala": "🇬🇹",
  "Honduran": "🇭🇳",
  "Honduras": "🇭🇳",
  "Hungarian": "🇭🇺",
  "Hungary": "🇭🇺",
  "Icelandic": "🇮🇸",
  "Iceland": "🇮🇸",
  "Indian": "🇮🇳",
  "India": "🇮🇳",
  "Indonesian": "🇮🇩",
  "Indonesia": "🇮🇩",
  "Iranian": "🇮🇷",
  "Iran": "🇮🇷",
  "Iraqi": "🇮🇶",
  "Iraq": "🇮🇶",
  "Irish": "🇮🇪",
  "Ireland": "🇮🇪",
  "Israeli": "🇮🇱",
  "Israel": "🇮🇱",
  "Italian": "🇮🇹",
  "Italy": "🇮🇹",
  "Jamaican": "🇯🇲",
  "Jamaica": "🇯🇲",
  "Japanese": "🇯🇵",
  "Japan": "🇯🇵",
  "Kazakhstani": "🇰🇿",
  "Kazakhstan": "🇰🇿",
  "Kosovan": "🇽🇰",
  "Kosovo": "🇽🇰",
  "Kyrgyzstani": "🇰🇬",
  "Kyrgyzstan": "🇰🇬",
  "Latvian": "🇱🇻",
  "Latvia": "🇱🇻",
  "Lebanese": "🇱🇧",
  "Lebanon": "🇱🇧",
  "Lithuanian": "🇱🇹",
  "Lithuania": "🇱🇹",
  "Luxembourg": "🇱🇺",
  "Macedonian": "🇲🇰",
  "North Macedonia": "🇲🇰",
  "Malaysian": "🇲🇾",
  "Malaysia": "🇲🇾",
  "Maltese": "🇲🇹",
  "Malta": "🇲🇹",
  "Mexican": "🇲🇽",
  "Mexico": "🇲🇽",
  "Moldovan": "🇲🇩",
  "Moldova": "🇲🇩",
  "Montenegrin": "🇲🇪",
  "Montenegro": "🇲🇪",
  "Moroccan": "🇲🇦",
  "Morocco": "🇲🇦",
  "New Zealander": "🇳🇿",
  "New Zealand": "🇳🇿",
  "Nigerian": "🇳🇬",
  "Nigeria": "🇳🇬",
  "Norwegian": "🇳🇴",
  "Norway": "🇳🇴",
  "Panamanian": "🇵🇦",
  "Panama": "🇵🇦",
  "Paraguayan": "🇵🇾",
  "Paraguay": "🇵🇾",
  "Peruvian": "🇵🇪",
  "Peru": "🇵🇪",
  "Philippine": "🇵🇭",
  "Philippines": "🇵🇭",
  "Polish": "🇵🇱",
  "Poland": "🇵🇱",
  "Portuguese": "🇵🇹",
  "Portugal": "🇵🇹",
  "Qatari": "🇶🇦",
  "Qatar": "🇶🇦",
  "Romanian": "🇷🇴",
  "Romania": "🇷🇴",
  "Russian": "🇷🇺",
  "Russia": "🇷🇺",
  "Salvadoran": "🇸🇻",
  "El Salvador": "🇸🇻",
  "Sammarinese": "🇸🇲",
  "San Marino": "🇸🇲",
  "Saudi": "🇸🇦",
  "Saudi Arabia": "🇸🇦",
  "Scottish": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Serbian": "🇷🇸",
  "Serbia": "🇷🇸",
  "Singaporean": "🇸🇬",
  "Singapore": "🇸🇬",
  "Slovak": "🇸🇰",
  "Slovakia": "🇸🇰",
  "Slovenian": "🇸🇮",
  "Slovenia": "🇸🇮",
  "South African": "🇿🇦",
  "South Africa": "🇿🇦",
  "South Korean": "🇰🇷",
  "Spanish": "🇪🇸",
  "Spain": "🇪🇸",
  "Swedish": "🇸🇪",
  "Sweden": "🇸🇪",
  "Swiss": "🇨🇭",
  "Switzerland": "🇨🇭",
  "Taiwanese": "🇹🇼",
  "Taiwan": "🇹🇼",
  "Tajikistani": "🇹🇯",
  "Tajikistan": "🇹🇯",
  "Thai": "🇹🇭",
  "Thailand": "🇹🇭",
  "Tunisian": "🇹🇳",
  "Tunisia": "🇹🇳",
  "Turkish": "🇹🇷",
  "Turkey": "🇹🇷",
  "Ukrainian": "🇺🇦",
  "Ukraine": "🇺🇦",
  "Uruguayan": "🇺🇾",
  "Uruguay": "🇺🇾",
  "Uzbekistani": "🇺🇿",
  "Uzbekistan": "🇺🇿",
  "Venezuelan": "🇻🇪",
  "Venezuela": "🇻🇪",
  "Welsh": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "Wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "Laotian": "🇱🇦",
  "Laos": "🇱🇦",
  "Northern Irish": "🏴󠁧󠁢󠁮󠁩󠁩󠁿",
  "Northern Ireland": "🏴󠁧󠁢󠁮󠁩󠁩󠁿",
  "Hong Kong": "🇭🇰",
  "Myanmar": "🇲🇲",
  "Gibraltarian": "🇬🇮",
  "Gibraltar": "🇬🇮",
};

export function getFlag(name: string): string {
  if (!name) return "🌍";
  // Check if it's already a flag (some manual inputs might be)
  if (name.length <= 2 && /[\uD83C][\uDDE6-\uDDFF][\uD83C][\uDDE6-\uDDFF]/.test(name)) return name;
  
  const flag = nationalityFlags[name];
  if (flag) return flag;
  
  // Try case-insensitive
  const entry = Object.entries(nationalityFlags).find(([key]) => key.toLowerCase() === name.toLowerCase());
  return entry ? entry[1] : "🌍";
}
