export const nationalityFlags: { [key: string]: string } = {
  "Afghan": "🇦🇫",
  "Albanian": "🇦🇱",
  "Algerian": "🇩🇿",
  "American": "🇺🇸",
  "Andorran": "🇦🇩",
  "Angolan": "🇦🇴",
  "Antiguan": "🇦🇬",
  "Argentine": "🇦🇷",
  "Argentinian": "🇦🇷",
  "Argentina": "🇦🇷",
  "Armenian": "🇦🇲",
  "Australian": "🇦🇺",
  "Austrian": "🇦🇹",
  "Azerbaijani": "🇦🇿",
  "Bahamian": "🇧🇸",
  "Bahraini": "🇧🇭",
  "Bangladeshi": "🇧🇩",
  "Barbadian": "🇧🇧",
  "Basotho": "🇱🇸",
  "Belarusian": "🇧🇾",
  "Belgian": "🇧🇪",
  "Belizean": "🇧🇿",
  "Beninese": "🇧🇯",
  "Bermudian": "🇧🇲",
  "Bhutanese": "🇧🇹",
  "Bissau-Guinean": "🇬🇼",
  "Bolivian": "🇧🇴",
  "Bosnian": "🇧🇦",
  "Botswanan": "🇧🇼",
  "Brazilian": "🇧🇷",
  "Brazil": "🇧🇷",
  "Bruneian": "🇧🇳",
  "Bulgarian": "🇧🇬",
  "Burkinese": "🇧🇫",
  "Burmese": "🇲🇲",
  "Burundian": "🇧🇮",
  "Cambodian": "🇰🇭",
  "Cameroonian": "🇨🇲",
  "Canadian": "🇨🇦",
  "Cape Verdean": "🇨🇻",
  "Central African": "🇨🇫",
  "Chadian": "🇹🇩",
  "Chilean": "🇨🇱",
  "Chinese": "🇨🇳",
  "Colombian": "🇨🇴",
  "Comorian": "🇰🇲",
  "Congolese (DR)": "🇨🇩",
  "Congolese (Republic)": "🇨🇬",
  "Costa Rican": "🇨🇷",
  "Croatian": "🇭🇷",
  "Cuban": "🇨🇺",
  "Curaçaoan": "🇨🇼",
  "Cypriot": "🇨🇾",
  "Czech": "🇨🇿",
  "Danish": "🇩🇰",
  "Dominican": "🇩🇲",
  "Dominican (Republic)": "🇩🇴",
  "Dutch": "🇳🇱",
  "Dutch (Aruba)": "🇦🇼",
  "Ecuadorean": "🇪🇨",
  "Egyptian": "🇪🇬",
  "Emirati": "🇦🇪",
  "English": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "English (Jersey)": "🇯🇪",
  "Equatorial Guinea": "🇬🇶",
  "Eritrean": "🇪🇷",
  "Estonian": "🇪🇪",
  "Ethiopian": "🇪🇹",
  "Faroese": "🇫🇴",
  "Fijian": "🇫🇯",
  "Finnish": "🇫🇮",
  "French": "🇫🇷",
  "French Guianan": "🇬🇫",
  "Gabonese": "🇬🇦",
  "Gambian": "🇬🇲",
  "Georgian": "🇬🇪",
  "German": "🇩🇪",
  "Ghanaian": "🇬🇭",
  "Gibraltarian": "🇬🇮",
  "Greek": "🇬🇷",
  "Grenadian": "🇬🇩",
  "Guadeloupean": "🇬🇵",
  "Guatemalan": "🇬🇹",
  "Guinean": "🇬🇳",
  "Guyanese": "🇬🇾",
  "Haitian": "🇭🇹",
  "Honduran": "🇭🇳",
  "Hong Kongese": "🇭🇰",
  "Hungarian": "🇭🇺",
  "Icelandic": "🇮🇸",
  "Indian": "🇮🇳",
  "Indonesian": "🇮🇩",
  "Iranian": "🇮🇷",
  "Iraqi": "🇮🇶",
  "Irish": "🇮🇪",
  "Israelian": "🇮🇱",
  "Italian": "🇮🇹",
  "Ivorian": "🇨🇮",
  "Jamaican": "🇯🇲",
  "Japanese": "🇯🇵",
  "Jordanian": "🇯🇴",
  "Kazakh": "🇰🇿",
  "Kenyan": "🇰🇪",
  "Kosovan": "🇽🇰",
  "Kuwaiti": "🇰🇼",
  "Kyrgyzstanian": "🇰🇬",
  "Laotian": "🇱🇦",
  "Latvian": "🇱🇻",
  "Lebanese": "🇱🇧",
  "Liberian": "🇱🇷",
  "Libyan": "🇱🇾",
  "Liechtensteinian": "🇱🇮",
  "Lithuanian": "🇱🇹",
  "Luxembourgian": "🇱🇺",
  "Macedonian": "🇲🇰",
  "North Macedonian": "🇲🇰",
  "Malagasy": "🇲🇬",
  "Malawian": "🇲🇼",
  "Malaysian": "🇲🇾",
  "Malian": "🇲🇱",
  "Maltese": "🇲🇹",
  "Martinican": "🇲🇶",
  "Mauritanian": "🇲🇷",
  "Mauritian": "🇲🇺",
  "Mexican": "🇲🇽",
  "Moldovan": "🇲🇩",
  "Mongolian": "🇲🇳",
  "Montenegrin": "🇲🇪",
  "Montserratian": "🇲🇸",
  "Moroccan": "🇲🇦",
  "Mozambican": "🇲🇿",
  "Namibian": "🇳🇦",
  "Nepalese": "🇳🇵",
  "New Caledonian": "🇳🇨",
  "New Zealandian": "🇳🇿",
  "Nicaraguan": "🇳🇮",
  "Nigerien": "🇳🇪",
  "Nigerian": "🇳🇬",
  "North Korean": "🇰🇵",
  "Northern Irish": "🏴󠁧󠁢󠁮󠁩󠁩󠁿",
  "Norwegian": "🇳🇴",
  "Omani": "🇴🇲",
  "Pakistani": "🇵🇰",
  "Palestinian": "🇵🇸",
  "Panamanian": "🇵🇦",
  "Paraguayan": "🇵🇾",
  "Peruvian": "🇵🇪",
  "Philippine": "🇵🇭",
  "Polish": "🇵🇱",
  "Portuguese": "🇵🇹",
  "Puerto Rican": "🇵🇷",
  "Qatari": "🇶🇦",
  "Romanian": "🇷🇴",
  "Russian": "🇷🇺",
  "Rwandan": "🇷🇼",
  "Saint Kitts and Nevis": "🇰🇳",
  "Saint Lucian": "🇱🇨",
  "Salvadorean": "🇸🇻",
  "Samoan": "🇼🇸",
  "San Marinian": "🇸🇲",
  "São Tomé and Príncipe": "🇸🇹",
  "Saudi Arabian": "🇸🇦",
  "Scottish": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Senegalese": "🇸🇳",
  "Serbian": "🇷🇸",
  "Sierra Leonian": "🇸🇱",
  "Singaporean": "🇸🇬",
  "Slovak": "🇸🇰",
  "Slovene": "🇸🇮",
  "Solomonislands": "🇸🇧",
  "Somali": "🇸🇴",
  "South African": "🇿🇦",
  "South Korean": "🇰🇷",
  "South Sudanese": "🇸🇸",
  "Spanish": "🇪🇸",
  "Sri Lankan": "🇱🇰",
  "Sudanese": "🇸🇩",
  "Surinamese": "🇸🇷",
  "Swazi": "🇸🇿",
  "Swedish": "🇸🇪",
  "Swiss": "🇨🇭",
  "Syrian": "🇸🇾",
  "Taiwanese": "🇹🇼",
  "Tajik": "🇹🇯",
  "Tanzanian": "🇹🇿",
  "Thai": "🇹🇭",
  "Togolese": "🇹🇬",
  "Trinidadian": "🇹🇹",
  "Tunisian": "🇹🇳",
  "Turkish": "🇹🇷",
  "Turkmen": "🇹🇲",
  "Ugandan": "🇺🇬",
  "Ukrainian": "🇺🇦",
  "Uruguayan": "🇺🇾",
  "Uzbek": "🇺🇿",
  "Vanuatuan": "🇻🇺",
  "Venezuelan": "🇻🇪",
  "Vincentians": "🇻🇨",
  "Welsh": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "Yemeni": "🇾🇪",
  "Zambian": "🇿🇲",
  "Zimbabwean": "🇿🇼"
};

export function getFlag(name: string): string {
  if (!name || typeof name !== 'string') return "🌍";
  
  const cleanName = name.trim();
  if (nationalityFlags[cleanName]) return nationalityFlags[cleanName];
  
  const lowerName = cleanName.toLowerCase();
  
  // Try exact lowecase match
  const match = Object.entries(nationalityFlags).find(([key]) => key.toLowerCase() === lowerName);
  if (match) return match[1];

  // Try partial match (e.g. "Arabs" -> "Saudi Arabia" or similar if needed)
  if (lowerName.includes('england')) return "🏴󠁧󠁢󠁥󠁮󠁧󠁿";
  if (lowerName.includes('spain')) return "🇪🇸";
  if (lowerName.includes('brazil')) return "🇧🇷";
  if (lowerName.includes('argentina')) return "🇦🇷";
  if (lowerName.includes('portugal')) return "🇵🇹";
  if (lowerName.includes('italy')) return "🇮🇹";
  if (lowerName.includes('france')) return "🇫🇷";
  if (lowerName.includes('germany')) return "🇩🇪";
  
  return "🌍";
}
