export const nationalityFlags: { [key: string]: string } = {
  // Nationalities (as stored in players.nationality)
  "Albanian": "🇦🇱",
  "Algerian": "🇩🇿",
  "American": "🇺🇸",
  "Andorran": "🇦🇩",
  "Angolan": "🇦🇴",
  "Argentinian": "🇦🇷",
  "Armenian": "🇦🇲",
  "Australian": "🇦🇺",
  "Austrian": "🇦🇹",
  "Azerbaijani": "🇦🇿",
  "Bahraini": "🇧🇭",
  "Belarusian": "🇧🇾",
  "Belgian": "🇧🇪",
  "Beninese": "🇧🇯",
  "Bolivian": "🇧🇴",
  "Bosnian": "🇧🇦",
  "Brazilian": "🇧🇷",
  "Bulgarian": "🇧🇬",
  "Burkinabe": "🇧🇫",
  "Burundian": "🇧🇮",
  "Cambodian": "🇰🇭",
  "Cameroonian": "🇨🇲",
  "Canadian": "🇨🇦",
  "Cape Verdean": "🇨🇻",
  "Central African": "🇨🇫",
  "Chadian": "🇹🇩",
  "Chilean": "🇨🇱",
  "Chinese": "🇨🇳",
  "Colombian": "🇨🇴",
  "Comoran": "🇰🇲",
  "Congolese": "🇨🇬",
  "Costa Rican": "🇨🇷",
  "Croatian": "🇭🇷",
  "Cuban": "🇨🇺",
  "Cypriot": "🇨🇾",
  "Czech": "🇨🇿",
  "Danish": "🇩🇰",
  "Djiboutian": "🇩🇯",
  "Dominican": "🇩🇴",
  "Dutch": "🇳🇱",
  "Ecuadorian": "🇪🇨",
  "Egyptian": "🇪🇬",
  "Emirati": "🇦🇪",
  "English": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "Equatoguinean": "🇬🇶",
  "Estonian": "🇪🇪",
  "Ethiopian": "🇪🇹",
  "Faroese": "🇫🇴",
  "Fijian": "🇫🇯",
  "Finnish": "🇫🇮",
  "French": "🇫🇷",
  "Gabonese": "🇬🇦",
  "Gambian": "🇬🇲",
  "Georgian": "🇬🇪",
  "German": "🇩🇪",
  "Ghanaian": "🇬🇭",
  "Greek": "🇬🇷",
  "Grenadian": "🇬🇩",
  "Guamanian": "🇬🇺",
  "Guatemalan": "🇬🇹",
  "Guinean": "🇬🇳",
  "Guyanese": "🇬🇾",
  "Haitian": "🇭🇹",
  "Honduran": "🇭🇳",
  "Hungarian": "🇭🇺",
  "Icelandic": "🇮🇸",
  "Indian": "🇮🇳",
  "Indonesian": "🇮🇩",
  "Iranian": "🇮🇷",
  "Iraqi": "🇮🇶",
  "Irish": "🇮🇪",
  "Israeli": "🇮🇱",
  "Italian": "🇮🇹",
  "Ivorian": "🇨🇮",
  "Jamaican": "🇯🇲",
  "Japanese": "🇯🇵",
  "Jordanian": "🇯🇴",
  "Kazakhstani": "🇰🇿",
  "Kenyan": "🇰🇪",
  "Kosovan": "🇽🇰",
  "Kuwaiti": "🇰🇼",
  "Kyrgyzstani": "🇰🇬",
  "Latvian": "🇱🇻",
  "Lebanese": "🇱🇧",
  "Lesotho": "🇱🇸",
  "Liberian": "🇱🇷",
  "Libyan": "🇱🇾",
  "Lithuanian": "🇱🇹",
  "Luxembourg": "🇱🇺",
  "Macedonian": "🇲🇰",
  "Malagasy": "🇲🇬",
  "Malawian": "🇲🇼",
  "Malaysian": "🇲🇾",
  "Malian": "🇲🇱",
  "Maltese": "🇲🇹",
  "Mauritanian": "🇲🇷",
  "Mauritian": "🇲🇺",
  "Mexican": "🇲🇽",
  "Moldovan": "🇲🇩",
  "Montenegrin": "🇲🇪",
  "Moroccan": "🇲🇦",
  "Mozambican": "🇲🇿",
  "Namibian": "🇳🇦",
  "Nepalese": "🇳🇵",
  "New Zealander": "🇳🇿",
  "Nicaraguan": "🇳🇮",
  "Niger": "🇳🇪",
  "Nigerian": "🇳🇬",
  "North Korean": "🇰🇵",
  "Norwegian": "🇳🇴",
  "Omani": "🇴🇲",
  "Pakistani": "🇵🇰",
  "Palestinian": "🇵🇸",
  "Panamanian": "🇵🇦",
  "Paraguayan": "🇵🇾",
  "Peruvian": "🇵🇪",
  "Philippine": "🇵🇭",
  "Polish": "🇵🇱",
  "Portuguese": "🇵🇹",
  "Puerto Rican": "🇵🇷",
  "Qatari": "🇶🇦",
  "Romanian": "🇷🇴",
  "Russian": "🇷🇺",
  "Rwandan": "🇷🇼",
  "Salvadoran": "🇸🇻",
  "Sammarinese": "🇸🇲",
  "Saudi": "🇸🇦",
  "Scottish": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Senegalese": "🇸🇳",
  "Serbian": "🇷🇸",
  "Sierra Leonean": "🇸🇱",
  "Singaporean": "🇸🇬",
  "Slovak": "🇸🇰",
  "Slovenian": "🇸🇮",
  "Somali": "🇸🇴",
  "South African": "🇿🇦",
  "South Korean": "🇰🇷",
  "South Sudanese": "🇸🇸",
  "Spanish": "🇪🇸",
  "Sudanese": "🇸🇩",
  "Surinamese": "🇸🇷",
  "Swazi": "🇸🇿",
  "Swedish": "🇸🇪",
  "Swiss": "🇨🇭",
  "Syrian": "🇸🇾",
  "Tagalog": "🇵🇭",
  "Taiwanese": "🇹🇼",
  "Tajikistani": "🇹🇯",
  "Tanzanian": "🇹🇿",
  "Thai": "🇹🇭",
  "Togolese": "🇹🇬",
  "Trinidadian": "🇹🇹",
  "Tunisian": "🇹🇳",
  "Turkish": "🇹🇷",
  "Turkmen": "🇹🇲",
  "Ugandan": "🇺🇬",
  "Ukrainian": "🇺🇦",
  "Uruguayan": "🇺🇾",
  "Uzbekistani": "🇺🇿",
  "Vanuatu": "🇻🇺",
  "Venezuelan": "🇻🇪",
  "Vietnamese": "🇻🇳",
  "Welsh": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "Yemeni": "🇾🇪",
  "Zambian": "🇿🇲",
  "Zimbabwean": "🇿🇼"
};

export function getFlag(name: string): string {
  if (!name) return "🌍";
  // Check if it's already a flag (some manual inputs might be)
  if (name.length <= 2 && /[\uD83C][\uDDE6-\uDDFF][\uD83C][\uDDE6-\uDDFF]/.test(name)) return name;
  
  const flag = nationalityFlags[name];
  if (flag) return flag;
  
  // Try case-insensitive
  const entry = Object.entries(nationalityFlags).find(([key]) => key.toLowerCase() === name.toLowerCase());
  return entry ? entry[1] : "🌍";
}
